# 網站基本設定
title: 我的部落格
description: 探索台南最道地的美味，品嚐在地人的私房推薦
baseurl: ""
url: "https://dssass.com"

# 作者資訊
author:
  name: 朱振均
  email: dss4129889@gmail.com

# 建置設定
markdown: kramdown
highlighter: rouge
theme: minima

# 外掛
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag



# 分類設定
# 我們讓 Jekyll 使用 Collections 的預設行為，這是最穩定的
collections:
  topics:
    output: true

# 預設值
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "朱"
  # 我們將 pages 的預設 layout 拿掉，讓每個頁面自己決定
  #- scope:
  #    path: ""
  #    type: "pages"
  #  values:
  #    layout: "default"
