# 工作流程的名稱
name: Build and Deploy Jekyll Site to SFTP

# 觸發條件：當推送到 main 分支時自動執行
on:
  push:
    branches:
      - main
  # 允許手動觸發
  workflow_dispatch:

# 工作任務
jobs:
  build-and-deploy:
    # 使用由 GitHub 提供的最新版 Ubuntu 虛擬電腦來執行
    runs-on: ubuntu-latest

    # 執行的步驟
    steps:
      # 步驟 1: 從儲存庫中取得您的程式碼
      - name: Checkout code
        uses: actions/checkout@v4

      # 步驟 2: 設定 Ruby 環境
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          # 使用與您本地相同的 Ruby 版本
          ruby-version: '3.1' 
          # 快取 bundle 安裝的套件，加速未來的執行
          bundler-cache: true

      # 步驟 3: 安裝相依套件 (如果快取沒有的話)
      - name: Install dependencies
        run: bundle install

      # 步驟 4: 編譯 Jekyll 網站
      - name: Build the site
        run: bundle exec jekyll build

      # 步驟 5: 使用 SFTP 將網站部署到您的主機
      - name: Deploy to SFTP
        uses: appleboy/sftp-action@v0.1.10 
          with:
            host: ${{ secrets.FTP_HOST }}
            port: ${{ secrets.FTP_PORT }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            # 要上傳的來源資料夾
            source: "_site/"
            # 要上傳到的目標資料夾
            target: ${{ secrets.REMOTE_PATH }}
