name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: bundle exec jekyll build

      # =============================================================
      #  ★★★ 這就是我們新增的「偵錯步驟」 ★★★
      #  這個步驟會列出 _site 資料夾裡的所有檔案，包括隱藏檔案
      # =============================================================
      - name: List files in the build directory
        run: ls -la ./_site

      - name: Deploy to SFTP using a different action
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_HOST }}
          port: ${{ secrets.FTP_PORT }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './_site/*'
          remote_path: ${{ secrets.REMOTE_PATH }}
          args: -a 
